export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH = 'SET_AUTH';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const ADMIN_AUTH_START = 'ADMIN_AUTH_START';
export const ADMIN_AUTH_SUCCESS = 'ADMIN_AUTH_SUCCESS';
export const ADMIN_AUTH_FAIL = 'ADMIN_AUTH_FAIL';
export const ADMIN_AUTH_LOGOUT = 'ADMIN_AUTH_LOGOUT';
export const ADMIN_SET_AUTH = 'ADMIN_SET_AUTH';
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';